### ISSUE TITLE
Make the disabling of the WordPress News widget togglable via a setting/hook

### ISSUE THREAD

**Issue by leonidasmi** [Eco-Mode-WP/Eco-Mode#36]
In the `DisableDashboardWidgets` we hardcodedly remove the `dashboard_primary` metabox.

Let's make that optional, via a filter first and via a togglable setting later.

Make sure to update the README with the new hook

**Comment by moritzbappert** [comment]
@leonidasmi I made this filterable. Please have a look at my code. ;)
